<font size=6>Assignment 1 PF4DS</font>

Instructor: Dr. Le Thanh Sach

Student: Huynh Nhu Hung - 2270712

| Group | Utility | Numpy | Tensorflow | Pytorch |
| --- | --- | --- | --- | --- |
| Array creation | Return random integers from low (inclusive) to high (exclusive) | np.random.randint() __[Link](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html)__ | tf.random.uniform() __[Link](https://www.tensorflow.org/api_docs/python/tf/random/uniform)__ | torch.randint() __[Link](https://pytorch.org/docs/stable/generated/torch.randint.html#torch.randint)__ |
|  | Create an array/tensor based on a given array-like | np.array() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.array.html)__ | tf.constant() __[Link](https://www.tensorflow.org/api_docs/python/tf/constant)__  | torch.tensor() __[Link](https://pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor)__ |
|  | Create an array of numbers in a range | np.arange() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)__ | tf.range() __[Link](https://www.tensorflow.org/api_docs/python/tf/range)__ | torch.arange() __[Link](https://pytorch.org/docs/stable/generated/torch.arange.html)__ |
|  | Return an array of zeros | np.zeros() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)__ | tf.zeros() __[Link](https://www.tensorflow.org/api_docs/python/tf/zeros)__ | torch.zeros() __[Link](https://pytorch.org/docs/stable/generated/torch.zeros.html#torch.zeros)__ |
|  | Create an array without specifying entries when given a shape | np.empty() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.empty.html)__ | tf.experimental.numpy.empty() __[Link](https://www.tensorflow.org/api_docs/python/tf/experimental/numpy/empty)__ | torch.empty() __[Link](https://pytorch.org/docs/stable/generated/torch.empty.html#torch.empty)__ |
|  | Create an identity matrix | np.identity() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.identity.html)__ | tf.eye() __[Link](https://www.tensorflow.org/api_docs/python/tf/eye)__ | torch.eye() __[Link](https://pytorch.org/docs/stable/generated/torch.eye.html#torch.eye)__ |
|  | Create an array of ones when given a shape | np.ones() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.ones.html)__ | tf.ones() __[Link](https://www.tensorflow.org/api_docs/python/tf/ones)__ | torch.ones() __[Link](https://pytorch.org/docs/stable/generated/torch.ones.html#torch.ones)__ |
|  | Create an array given shape and fill it with a value | np.full() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.full.html)__ | tf.fill() __[Link](https://www.tensorflow.org/api_docs/python/tf/fill)__ | torch.full() __[Link](https://pytorch.org/docs/stable/generated/torch.full.html#torch.full)__ |
|  | Create an array copy of the given object | np.copy() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.copy.html)__ | N/A | torch.clone() __[Link](https://pytorch.org/docs/stable/generated/torch.clone.html#torch.clone)__ |
|  | Create evenly spaced numbers over a specified interval | np.linspace() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)__ | tf.linspace() __[Link](https://www.tensorflow.org/api_docs/python/tf/linspace)__ | torch.linspace() __[Link](https://pytorch.org/docs/stable/generated/torch.linspace.html#torch.linspace)__ |
|  | Create a list of coordinate matrices from coordinate vectors | np.meshgrid() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.meshgrid.html#numpy-meshgrid)__ | tf.meshgrid() __[Link](https://www.tensorflow.org/api_docs/python/tf/meshgrid)__ | torch.meshgrid() __[Link](https://pytorch.org/docs/stable/generated/torch.meshgrid.html#torch.meshgrid)__ |
| Array-handling methods | Get the shape of an array | np.ndarray.shape __[Link](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html)__ | tf.Tensor.shape __[Link](https://www.tensorflow.org/api_docs/python/tf/Tensor#shape)__ | torch.Tensor.shape __[Link](https://pytorch.org/docs/stable/generated/torch.Tensor.shape.html#torch.Tensor.shape)__ |
|  |  | np.shape() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.shape.html)__ | tf.shape() __[Link](https://www.tensorflow.org/api_docs/python/tf/shape)__ | torch.Tensor.size() __[Link](https://pytorch.org/docs/stable/generated/torch.Tensor.size.html#torch.Tensor.size)__ |
|  | Reshape an array | np.reshape() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)__ | tf.reshape() __[Link](https://www.tensorflow.org/api_docs/python/tf/reshape)__ | torch.reshape() __[Link](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape)__ |
|  | Stack arrays on the first dimension | np.vstack() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html)__ | tf.concat() __[Link](https://www.tensorflow.org/api_docs/python/tf/concat)__ | torch.vstack() __[Link](https://pytorch.org/docs/stable/generated/torch.vstack.html#torch.vstack)__ |
|  | Stack arrays on the second dimension | np.hstack() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html)__ | tf.concat() __[Link](https://www.tensorflow.org/api_docs/python/tf/concat)__ | torch.hstack() __[Link](https://pytorch.org/docs/stable/generated/torch.hstack.html#torch.hstack)__ |
|  | Stack arrays on the third dimension | np.dstack() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.dstack.html#)__ | tf.concat() __[Link](https://www.tensorflow.org/api_docs/python/tf/concat)__ | torch.dstack() __[Link](https://pytorch.org/docs/stable/generated/torch.dstack.html#torch.dstack)__ |
|  | Return an array with axes transposed | np.transpose() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html)__ | tf.transpose() __[Link](https://www.tensorflow.org/api_docs/python/tf/transpose)__ | torch.permute() __[Link](https://pytorch.org/docs/stable/generated/torch.permute.html#torch.permute)__ |
|  | Returns an array with a dimension of size one inserted at the specified position | np.expand_dims() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html#numpy.expand_dims)__ | tf.expand_dims() __[Link](https://www.tensorflow.org/api_docs/python/tf/expand_dims)__ | torch.unsqueeze() __[Link](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html#torch.unsqueeze)__ |
|  | Join a sequence of arrays along an existing axis | np.concatenate() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)__ | tf.concat() __[Link](https://www.tensorflow.org/api_docs/python/tf/concat)__ | torch.cat() __[Link](https://pytorch.org/docs/stable/generated/torch.cat.html#torch.cat)__ |
| Math related commands | Test element-wise for NaN and return result as a boolean array | np.isnan() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.isnan.html)__ | tf.math.is_nan() __[Link](https://www.tensorflow.org/api_docs/python/tf/math/is_nan)__ | torch.isnan() __[Link](https://pytorch.org/docs/stable/generated/torch.isnan.html#torch.isnan)__ |
|  | Test element-wise for finiteness (not infinity and not NaN) | np.isfinite() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.isfinite.html)__ | tf.math.is_finite __[Link](https://www.tensorflow.org/api_docs/python/tf/math/is_finite)__ | torch.isfinite() __[Link](https://pytorch.org/docs/stable/generated/torch.isfinite.html#torch.isfinite)__ |
|  | Test element-wise for positive or negative infinity | np.isinf() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.isinf.html)__ | tf.math.is_inf() __[Link](https://www.tensorflow.org/api_docs/python/tf/math/is_inf)__ | torch.isinf() __[Link](https://pytorch.org/docs/stable/generated/torch.isinf.html#torch.isinf)__ |
|  | Round the elements in an array | np.round() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.round.html#numpy.round)__ | tf.round() __[Link](https://www.tensorflow.org/api_docs/python/tf/math/round)__ | torch.round() __[Link](https://pytorch.org/docs/stable/generated/torch.round.html#torch.round)__ |
|  | Return the sum of an array or sum along an axis | np.sum() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.sum.html)__ | tf.reduce_sum() __[Link](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum)__ | torch.sum() __[Link](https://pytorch.org/docs/stable/generated/torch.sum.html#torch.sum)__ |
|  | Return the maximum of an array or maximum along an axis | np.max() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.max.html)__ | tf.reduce_max() __[Link](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max)__ | torch.max() __[Link](https://pytorch.org/docs/stable/generated/torch.max.html#torch.max)__ |
|  | Return the minimum of an array or minimum along an axis | np.min() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.min.html)__ | tf.reduce_min() __[Link](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min)__ | torch.min() __[Link](https://pytorch.org/docs/stable/generated/torch.min.html#torch.min)__ |
|  | Return the mean of an array or mean along an axis | np.mean() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.mean.html)__ | tf.reduce_mean() __[Link](https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean)__ | torch.mean() __[Link](https://pytorch.org/docs/stable/generated/torch.mean.html#torch.mean)__ |
|  | Add arrays element-wise | np.add() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.add.html)__ | tf.add() __[Link](https://www.tensorflow.org/api_docs/python/tf/math/add)__ | torch.add() __[Link](https://pytorch.org/docs/stable/generated/torch.add.html#torch.add)__ |
|  | Subtract arrays element-wise | np.subtract() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.subtract.html)__ | tf.subtract() __[Link](https://www.tensorflow.org/api_docs/python/tf/math/subtract)__ | torch.sub() __[Link](https://pytorch.org/docs/stable/generated/torch.sub.html#torch.sub)__ |
|  | Multiply arrays element-wise | np.multiply() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.multiply.html)__ | tf.multiply() __[Link](https://www.tensorflow.org/api_docs/python/tf/math/multiply)__ | torch.mul() __[Link](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul)__ |
|  | First array elements raised to powers from second array, element-wise | np.power() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.power.html)__ | tf.pow() __[Link](https://www.tensorflow.org/api_docs/python/tf/math/pow)__ | torch.pow() __[Link](https://pytorch.org/docs/stable/generated/torch.pow.html#torch.pow)__ |
|  | Return the cumulative sum of the elements along a given axis | np.cumsum() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html)__ | tf.cumsum() __[Link](https://www.tensorflow.org/api_docs/python/tf/math/cumsum)__ | torch.cumsum() __[Link](https://pytorch.org/docs/stable/generated/torch.cumsum.html#torch.cumsum)__ |
|  | Compute the determinant of an array | np.linalg.det() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html#numpy.linalg.det)__ | tf.linalg.det() __[Link](https://www.tensorflow.org/api_docs/python/tf/linalg/det)__ | torch.det() __[Link](https://pytorch.org/docs/stable/generated/torch.linalg.det.html#torch.linalg.det)__ |
|  | Return the sum along diagonals of the array | np.trace() __[Link](https://numpy.org/doc/stable/reference/generated/numpy.trace.html)__ | tf.linalg.trace() __[Link](https://www.tensorflow.org/api_docs/python/tf/linalg/trace)__ | torch.trace() __[Link](https://pytorch.org/docs/stable/generated/torch.trace.html#torch.trace)__ |

In [1]:
import numpy as np
import tensorflow as tf
import torch

# Return random integers from low (inclusive) to high (exclusive)

In [7]:
np.random.randint(0, 10, (3, 2))

array([[8, 6],
       [7, 4],
       [5, 5]])

In [8]:
tf.random.uniform((3, 2), 0, 10, dtype=tf.dtypes.int32)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[8, 4],
       [0, 3],
       [0, 5]], dtype=int32)>

In [9]:
torch.randint(0, 10, (3, 2))

tensor([[9, 0],
        [3, 4],
        [3, 0]])

# Create an array/tensor based on a given array-like

In [10]:
lst = [[1, 2, 3], [4, 5, 6]]
lst

[[1, 2, 3], [4, 5, 6]]

In [11]:
np.array(lst)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
tf.constant(lst)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [13]:
torch.tensor(lst)

tensor([[1, 2, 3],
        [4, 5, 6]])

# Create an array of numbers in a range

In [16]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [15]:
tf.range(1, 10, 3)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 7], dtype=int32)>

In [17]:
torch.arange(1, 8, 1.5)

tensor([1.0000, 2.5000, 4.0000, 5.5000, 7.0000])

# Return an array of zeros

In [18]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
tf.zeros((1, 5))

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=array([[0., 0., 0., 0., 0.]], dtype=float32)>

In [20]:
torch.zeros((2, 5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

# Create an array without specifying entries when given a shape

In [21]:
np.empty((3, 6))

array([[4.72650757e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 3.95252517e-322,
        3.95252517e-322, 4.72650757e-310, 6.42285340e-323],
       [8.38967362e+242, 2.29983418e-312, 4.72707762e-310,
        6.42285340e-323, 9.82176261e+252, 1.02340333e-312]])

In [22]:
tf.experimental.numpy.empty((4, 5))

<tf.Tensor: shape=(4, 5), dtype=float64, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])>

In [23]:
torch.empty((5, 4))

tensor([[-5.3302e-29,  3.1215e-41, -5.3303e-29,  3.1215e-41],
        [ 1.8617e+25,  2.0318e-10,  8.6378e-04,  2.6221e+20],
        [ 1.8968e+31,  7.1481e+22,  4.3059e+21,  1.6028e-10],
        [ 2.9423e+26,  1.2927e+22,  4.3066e+21,  1.3102e+10],
        [ 4.4290e-39,  1.7300e-41,  6.8664e-44,  0.0000e+00]])

# Create an identity matrix

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
tf.eye(4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [26]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

#	Create an array of ones when given a shape

In [27]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [28]:
tf.ones((3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [29]:
torch.ones((4, 6))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

#	Create an array given shape and fill it with a value

In [30]:
np.full((3, 2), 1)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [31]:
tf.fill((6, 1), 5)

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[5],
       [5],
       [5],
       [5],
       [5],
       [5]], dtype=int32)>

In [32]:
torch.full((3, 2), 2)

tensor([[2, 2],
        [2, 2],
        [2, 2]])

#	Create an array copy of the given object

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr1 = arr
arr1[0][1] = 100
print("arr:", arr)
print("arr1:", arr1)

arr: [[  1 100   3]
 [  4   5   6]]
arr1: [[  1 100   3]
 [  4   5   6]]


In [36]:
arr2 = np.copy(arr)
arr2[0][1] = 1000
print("arr:", arr)
print("arr1:", arr2)

arr: [[  1 100   3]
 [  4   5   6]]
arr1: [[   1 1000    3]
 [   4    5    6]]


# Create evenly spaced numbers over a specified interval

In [37]:
np.linspace(10, 20, num=4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [38]:
tf.linspace(4, 50, num=7)

<tf.Tensor: shape=(7,), dtype=float64, numpy=
array([ 4.        , 11.66666667, 19.33333333, 27.        , 34.66666667,
       42.33333333, 50.        ])>

In [40]:
torch.linspace(1, 10, steps=10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Create a list of coordinate matrices from coordinate vectors

In [41]:
nx, ny = (4, 5)

In [42]:
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
print(x, y)
xv, yv = np.meshgrid(x, y)
print(xv)
print(yv)

[0.         0.33333333 0.66666667 1.        ] [0.   0.25 0.5  0.75 1.  ]
[[0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]]
[[0.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25]
 [0.5  0.5  0.5  0.5 ]
 [0.75 0.75 0.75 0.75]
 [1.   1.   1.   1.  ]]


In [43]:
x = tf.linspace(0, 1, nx)
y = tf.linspace(0, 1, ny)
print(x, y)
xv, yv = tf.meshgrid(x, y)
print(xv)
print(yv)

tf.Tensor([0.         0.33333333 0.66666667 1.        ], shape=(4,), dtype=float64) tf.Tensor([0.   0.25 0.5  0.75 1.  ], shape=(5,), dtype=float64)
tf.Tensor(
[[0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.33333333 0.66666667 1.        ]], shape=(5, 4), dtype=float64)
tf.Tensor(
[[0.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25]
 [0.5  0.5  0.5  0.5 ]
 [0.75 0.75 0.75 0.75]
 [1.   1.   1.   1.  ]], shape=(5, 4), dtype=float64)


In [44]:
x = torch.linspace(0, 1, nx)
y = torch.linspace(0, 1, ny)
print(x, y)
xv, yv = torch.meshgrid(x, y)
print(xv)
print(yv)

tensor([0.0000, 0.3333, 0.6667, 1.0000]) tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.3333, 0.3333],
        [0.6667, 0.6667, 0.6667, 0.6667, 0.6667],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])
tensor([[0.0000, 0.2500, 0.5000, 0.7500, 1.0000],
        [0.0000, 0.2500, 0.5000, 0.7500, 1.0000],
        [0.0000, 0.2500, 0.5000, 0.7500, 1.0000],
        [0.0000, 0.2500, 0.5000, 0.7500, 1.0000]])


/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


# Get the shape of an array

In [46]:
arr = np.random.rand(1, 2)
print(arr.shape)
print(np.shape(arr))

(1, 2)
(1, 2)


In [47]:
arr1 = tf.random.uniform((3, 5))
print(arr1.shape)
print(np.shape(arr1))

(3, 5)
(3, 5)


In [48]:
arr2 = torch.rand((3, 4))
print(arr2.shape)
print(np.shape(arr2))

torch.Size([3, 4])
torch.Size([3, 4])


# Reshape an array

In [53]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
torch_tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape, torch_tensor.shape)

(3, 3) torch.Size([3, 3])


In [50]:
np.reshape(arr, (1, -1)).shape

(1, 9)

In [51]:
tf.reshape(arr, (9, -1)).shape

TensorShape([9, 1])

In [54]:
torch.reshape(torch_tensor, (1, 9)).shape

torch.Size([1, 9])

# Stack arrays on the first dimension

In [55]:
arr1 = np.zeros((2, 3))
arr2 = np.ones((5, 3))
print(arr1.shape)
print(arr2.shape)
print(np.vstack((arr1, arr2)).shape)

(2, 3)
(5, 3)
(7, 3)


In [58]:
tf1 = tf.zeros((3, 2))
tf2 = tf.ones((5, 2))
print(tf1.shape)
print(tf2.shape)
print(tf.concat((tf1, tf2), axis=0).shape)

(3, 2)
(5, 2)
(8, 2)


In [59]:
torch_tensor1 = torch.zeros((1, 2))
torch_tensor2 = torch.ones((5, 2))
print(torch_tensor1.shape)
print(torch_tensor2.shape)
print(torch.vstack((torch_tensor1, torch_tensor2)).shape)

torch.Size([1, 2])
torch.Size([5, 2])
torch.Size([6, 2])


# Stack arrays on the second dimension

In [60]:
arr1 = np.zeros((1, 3))
arr2 = np.ones((1, 4))
print(arr1.shape)
print(arr2.shape)
print(np.hstack((arr1, arr2)).shape)

(1, 3)
(1, 4)
(1, 7)


In [61]:
tf1 = tf.zeros((3, 5))
tf2 = tf.ones((3, 2))
print(tf1.shape)
print(tf2.shape)
print(tf.concat((tf1, tf2), axis=1).shape)

(3, 5)
(3, 2)
(3, 7)


In [62]:
torch_tensor1 = torch.zeros((3, 2))
torch_tensor2 = torch.ones((3, 3))
print(torch_tensor1.shape)
print(torch_tensor2.shape)
print(torch.hstack((torch_tensor1, torch_tensor2)).shape)

torch.Size([3, 2])
torch.Size([3, 3])
torch.Size([3, 5])


# Stack arrays on the third dimension

In [63]:
arr1 = np.zeros((1, 2, 3))
arr2 = np.ones((1, 2, 4))
print(arr1.shape)
print(arr2.shape)
print(np.dstack((arr1, arr2)).shape)

(1, 2, 3)
(1, 2, 4)
(1, 2, 7)


In [64]:
tf1 = tf.zeros((3, 5, 2))
tf2 = tf.ones((3, 5, 1))
print(tf1.shape)
print(tf2.shape)
print(tf.concat((tf1, tf2), axis=2).shape)

(3, 5, 2)
(3, 5, 1)
(3, 5, 3)


In [66]:
torch_tensor1 = torch.zeros((3, 3, 4))
torch_tensor2 = torch.ones((3, 3, 3))
print(torch_tensor1.shape)
print(torch_tensor2.shape)
print(torch.dstack((torch_tensor1, torch_tensor2)).shape)

torch.Size([3, 3, 4])
torch.Size([3, 3, 3])
torch.Size([3, 3, 7])


# Return an array with axes transposed

In [68]:
arr = np.zeros((3, 4))
np.transpose(arr).shape

(4, 3)

In [69]:
arr = tf.zeros((2, 3))
tf.transpose(arr).shape

TensorShape([3, 2])

In [72]:
arr = torch.zeros((4, 1))
torch.permute(arr, dims=(1,0)).shape

torch.Size([1, 4])

#	Returns an array with a dimension of size one inserted at the specified position

In [73]:
arr = np.zeros((3, 5))
np.expand_dims(arr, axis=2).shape

(3, 5, 1)

In [75]:
arr = tf.zeros((2, 5))
tf.expand_dims(arr, axis=1).shape

TensorShape([2, 1, 5])

In [76]:
arr = torch.zeros((4, 5))
torch.unsqueeze(arr, dim=0).shape

torch.Size([1, 4, 5])

# Join a sequence of arrays along an existing axis

In [78]:
arr1 = np.zeros((3, 4))
arr2 = np.zeros((4, 4))
np.concatenate((arr1, arr2), axis=0).shape

(7, 4)

In [79]:
arr1 = tf.zeros((4, 5))
arr2 = tf.zeros((4, 4))
tf.concat((arr1, arr2), axis=1).shape

TensorShape([4, 9])

In [81]:
arr1 = torch.zeros((2, 2))
arr2 = torch.zeros((2, 2))
torch.cat((arr1, arr2), axis=1).shape

torch.Size([2, 4])

# Test element-wise for NaN/inf/finiteness and return result as a boolean array

In [89]:
arr = np.array([[np.nan, np.inf, np.nan], [1, 2, 3], [3, 4, np.nan]])
torch_tensor = torch.tensor([[np.nan, np.inf, np.nan], [1, 2, 3], [3, 4, np.nan]])

In [90]:
print(np.isnan(arr))
print(np.isfinite(arr))
print(np.isinf(arr))

[[ True False  True]
 [False False False]
 [False False  True]]
[[False False False]
 [ True  True  True]
 [ True  True False]]
[[False  True False]
 [False False False]
 [False False False]]


In [91]:
print(tf.math.is_nan(arr))
print(tf.math.is_finite(arr))
print(tf.math.is_inf(arr))

tf.Tensor(
[[ True False  True]
 [False False False]
 [False False  True]], shape=(3, 3), dtype=bool)
tf.Tensor(
[[False False False]
 [ True  True  True]
 [ True  True False]], shape=(3, 3), dtype=bool)
tf.Tensor(
[[False  True False]
 [False False False]
 [False False False]], shape=(3, 3), dtype=bool)


In [92]:
print(torch.isnan(torch_tensor))
print(torch.isfinite(torch_tensor))
print(torch.isinf(torch_tensor))

tensor([[ True, False,  True],
        [False, False, False],
        [False, False,  True]])
tensor([[False, False, False],
        [ True,  True,  True],
        [ True,  True, False]])
tensor([[False,  True, False],
        [False, False, False],
        [False, False, False]])


# Round the elements in an array

In [93]:
arr = np.random.rand(3, 4)
np.round(arr, decimals=2)

array([[0.81, 0.8 , 0.01, 0.96],
       [0.56, 0.03, 0.14, 0.75],
       [0.94, 0.93, 0.69, 0.3 ]])

In [95]:
arr = tf.random.uniform((2, 3))
tf.round(arr)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [0., 1., 0.]], dtype=float32)>

In [97]:
arr = torch.rand((3, 4))
torch.round(arr, decimals=2)

tensor([[0.9900, 0.2900, 0.9600, 0.4300],
        [0.3100, 0.9100, 0.2300, 0.0700],
        [0.4800, 0.4700, 0.5300, 0.8000]])

# Calculate add, subtract, multiply, and power element-wise

In [104]:
a = np.full((1, 2), 2)
b = np.full((1, 2), 3)
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.power(a, b))

[[5 5]]
[[-1 -1]]
[[6 6]]
[[8 8]]


In [106]:
a = tf.fill((1, 2), 2)
b = tf.fill((1, 2), 3)
print(tf.add(a, b))
print(tf.subtract(a, b))
print(tf.multiply(a, b))
print(tf.pow(a, b))

tf.Tensor([[5 5]], shape=(1, 2), dtype=int32)
tf.Tensor([[-1 -1]], shape=(1, 2), dtype=int32)
tf.Tensor([[6 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[8 8]], shape=(1, 2), dtype=int32)


In [107]:
a = torch.full((1, 2), 2)
b = torch.full((1, 2), 3)
print(torch.add(a, b))
print(torch.sub(a, b))
print(torch.mul(a, b))
print(torch.pow(a, b))

tensor([[5, 5]])
tensor([[-1, -1]])
tensor([[6, 6]])
tensor([[8, 8]])


# Get the sum, max, min, and mean of the array elements over a given axis

In [111]:
arr = np.reshape(np.arange(20),(4,-1))
print(np.sum(arr, axis=0))
print(np.max(arr, axis=0))
print(np.min(arr, axis=0))
print(np.mean(arr, axis=0))

[30 34 38 42 46]
[15 16 17 18 19]
[0 1 2 3 4]
[ 7.5  8.5  9.5 10.5 11.5]


In [117]:
arr = tf.reshape(tf.range(20, dtype=tf.float32),(4,-1))
print(tf.reduce_sum(arr, axis=0))
print(tf.reduce_max(arr, axis=0))
print(tf.reduce_min(arr, axis=0))
print(tf.reduce_mean(arr, axis=0))

tf.Tensor([30. 34. 38. 42. 46.], shape=(5,), dtype=float32)
tf.Tensor([15. 16. 17. 18. 19.], shape=(5,), dtype=float32)
tf.Tensor([0. 1. 2. 3. 4.], shape=(5,), dtype=float32)
tf.Tensor([ 7.5  8.5  9.5 10.5 11.5], shape=(5,), dtype=float32)


In [116]:
arr = torch.reshape(torch.arange(20, dtype=torch.float32),(4,-1))
print(torch.sum(arr, dim=0))
print(torch.max(arr, dim=0))
print(torch.min(arr, dim=0))
print(torch.mean(arr, dim=0))

tensor([30., 34., 38., 42., 46.])
torch.return_types.max(
values=tensor([15., 16., 17., 18., 19.]),
indices=tensor([3, 3, 3, 3, 3]))
torch.return_types.min(
values=tensor([0., 1., 2., 3., 4.]),
indices=tensor([0, 0, 0, 0, 0]))
tensor([ 7.5000,  8.5000,  9.5000, 10.5000, 11.5000])


# Return the cumulative sum of the elements along a given axis

In [121]:
arr = np.random.randint(0, 10, (2, 4))
print(arr)
print(np.cumsum(arr, axis=0))
print(np.cumsum(arr, axis=1))

[[0 1 5 9]
 [2 2 4 6]]
[[ 0  1  5  9]
 [ 2  3  9 15]]
[[ 0  1  6 15]
 [ 2  4  8 14]]


In [124]:
arr = tf.random.uniform((2, 4), 0, 10, dtype=tf.int32)
print(arr)
print(tf.cumsum(arr, axis=0))
print(tf.cumsum(arr, axis=1))

tf.Tensor(
[[4 0 4 3]
 [6 1 0 7]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 4  0  4  3]
 [10  1  4 10]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 4  4  8 11]
 [ 6  7  7 14]], shape=(2, 4), dtype=int32)


In [125]:
arr = torch.randint(0, 10, (2, 4))
print(arr)
print(torch.cumsum(arr, dim=0))
print(torch.cumsum(arr, dim=1))

tensor([[6, 8, 9, 0],
        [0, 4, 0, 5]])
tensor([[ 6,  8,  9,  0],
        [ 6, 12,  9,  5]])
tensor([[ 6, 14, 23, 23],
        [ 0,  4,  4,  9]])


# Compute the determinant and trace of an array

In [139]:
arr = np.reshape(np.arange(9), (3,3))
print(np.linalg.det(arr))
print(np.trace(arr))

0.0
12


In [140]:
arr = tf.reshape(tf.range(9, dtype=tf.float32), (3,3))
print(tf.linalg.det(arr))
print(tf.linalg.trace(arr))

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(12.0, shape=(), dtype=float32)


In [138]:
arr = torch.reshape(torch.arange(9, dtype=torch.float32), (3,3))
print(torch.det(arr))
print(torch.trace(arr))

tensor(0.)
tensor(12.)
